### ISSUE TITLE
Defining derivatives in a chain

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bep021#8]
**NOTE** This stems from the bids derivatives workshop Copenhagen 2023

---

How to define derivatives in a "chain"?

Usually this is done via the [Sources](https://bids-specification.readthedocs.io/en/latest/glossary.html#sources-metadata) metadata. However, it might be nice to document the processing chain more explicitly, for example in the entities:

1. `<source_entities>_desc-downsampled_<suffix>.<ext>`
1. `<source_entities>_desc-downsampled+filtered_<suffix>.<ext>`

--> problem: this would result in very long filenames fairly quickly.

Alternatively, one could have much shorter labels for the preprocessing steps:

1. `<source_entities>_desc-ds+filt_<suffix>.<ext>`

--> problem: short labels like "ds" may be too general (i.e., take up a lot of "namespace")

Another alternative would be to have "generic" desc labels with an "inbuilt" index (`label1`, `label2`, etc.):

1. `<source_entities>_desc-preproc1_<suffix>.<ext>`
1. `<source_entities>_desc-preproc2_<suffix>.<ext>`
1. `<source_entities>_desc-preproc3_<suffix>.<ext>`

paired with a: `<source_entities>_<suffix>.json`

that is organized as:

```JSON
{
    "PreprocessingChain": {
        "preproc1": "downsampling",
        "preproc2": "filtering",
        "preproc3": "..."
    }
}
```

--> Important note: order in a JSON object should have a meaning ... if it doesn't (to be clarified), we might need to use a JSON array.

More complete example:

```YAML
{
    "PreprocessingChain": {
        "preproc1": "downsampling",
        "preproc2": "filtering",
        "preproc3": "..."
    },
    "downsampling": {
        "description": "lorem ipsum",
        "Sources": "bids::<source_entities>_<suffix>.<ext>",
        "Anti-aliasing-filter": "<link to key-value pair in SoftwareFilters>",
        "Method": "downsampling method (e.g., decimation --> taking every nth sample; or something else)",
    	"SamplingRate": 300
    },
    "filtering": {
        ... 
    }   
}
```

**Comment by christinerogers** [comment]
> short labels like "ds" may be too general (i.e., take up a lot of "namespace"

`ds` is probably best avoided given 30+ datasets in [bids-examples](https://github.com/bids-standard/bids-examples) are known by their `ds` number from openneuro etc

**Comment by robertoostenveld** [comment]
```YAML
{
    "PreprocessingChain": [
    "downsampling": {
        "description": "lorem ipsum",
        "Sources": "bids::<source_entities>_<suffix>.<ext>",
        "Anti-aliasing-filter": "<link to key-value pair in SoftwareFilters>",
        "Method": "downsampling method (e.g., decimation --> taking every nth sample; or something else)",
    	"SamplingRate": 300
    },
    "filtering": {
        ... 
    }  
]
}
```

**Comment by arnodelorme** [comment]
no "custom fields"

```YAML
{
    "PreprocessingChain": [
    {
        "Description": "downsampling 250 hz", [MANDATORY]
        "Sources": "bids::<source_entities>_<suffix>.<ext>", [MANDATORY]
        "<some fixed, defined name (tbd) indicating more info here>": { [OPTIONAL]
            "foo": "bar",
            "SamplingRate": 300
        }
    },
    {
        "Description": "HP filtering 1hz",
        ... 
    }  
]
}
```

**Comment by dorahermes** [comment]
Note - if the processing in the chain updates fields in the original _ieeg.json, these fields should be updated or removed.

**Comment by robertoostenveld** [comment]
```YAML
    "GeneratedBy": [
    {
        "Name": "downsampling", [MANDATORY]
        "Description": "downsampling 250 hz", [OPTIONAL]
        "Sources": "bids::<source_entities>_<suffix>.<ext>", [OPTIONAL]
        "<some name indicating more info here>": { [OPTIONAL]
            "foo": "bar",
            "SamplingRate": 300
        }
    },
    {
        "Name": "filtering", [MANDATORY]
        "description": "HP filtering 1hz", [OPTIONAL]
        ... 
    }  
   ]
````

**Comment by arnodelorme** [comment]
```YAML
    "<ProcessingChain>": [
    {
        "Name": "downsampling", [OPTIONAL]
        "Description": "Downsampling data at 250hz", [OPTIONAL]
        "Version": "0.1, [OPTIONAL]
        "Container": { [OPTIONAL]
            "foo": "bar",
            "SamplingRate": 300
        }
        "Sources": ["bids:<raw>:sub-001/eeg/xxx_eeg.edf"]
    },
    {
        "Name": "Filtering", [MANDATORY]
        "Description": "HP filtering 1hz", [OPTIONAL]
        "Sources": ["bids::sub-001/eeg/xxx_desc-downsample_eeg.edf"]
    }  
   ]
````
